name: Build and Deploy Spring Boot with Docker

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Build the Spring Boot app using Maven (you can replace with Gradle if you're using it)
      - name: Build Spring Boot App with Maven
        run: mvn clean package -DskipTests

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t springboot-app:latest .

      # Optionally, you can run the Docker container locally in the pipeline (to test)
      - name: Run Docker container locally
        run: |
          docker run -d -p 8080:8080 springboot-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure build job runs first

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker (containerd is used by Rancher Desktop)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Deploy Docker container to Rancher Desktop (or any other Docker-compatible environment)
      - name: Deploy Docker container to Rancher Desktop
        run: |
          docker run -d -p 8080:8080 springboot-app:latest

      # Optionally, check the running Docker containers
      - name: Check running Docker containers
        run: |
          docker ps
