name: Build and Deploy Spring Boot with Docker

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 using a specific distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'  # Specify the OpenJDK distribution

      # Build the Spring Boot app using Maven (you can replace with Gradle if you're using it)
      - name: Build Spring Boot App with Maven
        run: mvn clean package -DskipTests

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t springboot-app:latest .

      # Optionally, you can run the Docker container locally in the pipeline (to test)
      - name: Run Docker container locally
        run: |
          docker run -d -p 8080:8080 springboot-app:latest
