jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Verify contents of the directory (to make sure the pom.xml is present)
      - name: List project directory
        run: ls -al

      # Set up Oracle JDK 17
      - name: Set up Oracle JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oraclejdk'

      # Build the Spring Boot app using Maven
      - name: Build Spring Boot App with Maven
        run: mvn clean package -DskipTests
